export const entity = {
  WorkOrder: 2,
  Incoming: 3,
  JobNorms: 4,
  AllTask: 5,
  MyTask: 6,
  Despatch: 30,
  WOStage: 8,
  WOService: 9,
  StageMaster: 11,
  AcivityMaster: 12,
  DivisionMaster: 13,
  SubDivisionMaster: 14,
  LocationMaster: 15,
  ColorMaster: 16,
  SoftwareMaster: 17,
  Dashboard: 19,
  WorkflowList: 20,
  ComposingView: 21,
  TemplateUploader: 22,
  TemplateCreate: 63,
  ActivityConfigurtion: 23,
  UserListMaster: 26,
  UserRoleMaster: 31,
  UserSkillMaster: 32,
  ViewDespatch: 33,
  UOMUpdate: 28,
  WOStageHistory: 37,
  GraphicArt: 36,
  GraphicArtAudit: 38,
  HistoryIncomingSlot: 39,
  WOInstructions: 40,
  FilesUpload: 41,
  JournalMaster: 42,
  UnassignedArticle: 43,
  ToolMaster: 46,
  Query: 47,
  ToolsRunningStatus: 48,
  Norms: 49,
  Notifications: 50,
  NotificationsTemplate: 51,
  SenderEmailTemplate: 52,
  CheckListMaster: 53,
  fileTransfer: 54,
  fileTransferHistory: 55,
  ToolsConfiguration: 56,
  FileStatusReport: 57,
  FtpConfiguration: 58,
  WIPReport: 25,
  LibraryRepository: 63,
  Reset: 62,
  EmailTrigger: 44,
  TrackitAPIAudit: 45,
  Productivity_Summary_Report: 64,
  WIPEngine: 61,
  WIPLock: 65,
  WIPCUPJournalReport: 66,
  StageCreatedReport: 73,
  DownloadManuscript: 67,
  ManuscriptStatus: 72,
  activityTrack: 68,
  ActivityInterval:69,
  DeliveryMonitoringReport:76,
  JobSummaryReport : 74,
  IncomingDetails:77,
  DespatchFailureReport:78,
  FTPAuditReport:93,
  GraphicImageDelete:80,
  WipEngineActivityReport:81,
  ToolWIP:82,
  SoftMaster:88,
  ToolsAudit: 79,
  FTPDownloadStatus :94,
  //new_itracks 
  itracksFeedbackView: 70,
  AuditReport:83,
  ToolsAccessRights:89,
  CompletedWorkOrders:92,
  DownloadUploadManuscriptReport:98,
  masterWorkflow:96,
  ACSFTPDownloadStatusReport:120,
  ACSCopyeditingQue:133,
  //new_itracks 
  salesPMOPlanning: 132,

  //OUP Journals
  SwiftXMLReport: 146,
  LicenseChaser: 147,
  IssueProofQueue: 148,
  WIPHourReport: 134,
  WIPACSReporttest: 145,
  WIPSpringerReport: 135 ,
  WIPElseiver: 191,
  InflowElseiver: 205,
  OutflowReport: 207,
};
