export const appConfig = {
  server: {
    host: process.env.REACT_APP_SERVER_HOST,
    port: process.env.REACT_APP_SERVER_PORT,
    protocol: process.env.REACT_APP_SERVER_PROTOCOL,
    basePath: process.env.REACT_APP_SERVER_BASE_PATH || "",
    getUrl: () =>
      `${process.env.REACT_APP_SERVER_PROTOCOL}://${process.env.REACT_APP_SERVER_HOST
      }:${process.env.REACT_APP_SERVER_PORT}${process.env.REACT_APP_SERVER_BASE_PATH || ""
      }`,
    getSocketUrl: () =>
      window.localStorage.getItem("IN_DESKTOP_ENV") == "true"
        ? `ws://localhost:${localStorage.getItem("api_port")}/iwmsSocket`
        : `${process.env.REACT_APP_WS_URL}`,
    getSocketServerUrl: () => `${process.env.REACT_APP_WS_URL}`,
    getItrackUrl: () =>
      `${process.env.REACT_APP_SERVER_PROTOCOL}://${process.env.REACT_APP_SERVER_HOST
      }:${process.env.REACT_APP_SERVER_PORT}${process.env.REACT_APP_SERVER_BASE_PATH || ""
      }`,
  },
  clientUtility: {
    version: process.env.REACT_APP_CLIENT_UTILITY_VERSION,
    mode: process.env.REACT_APP_MODE,
    protocol: "iwms:",
    delimitter: ":::",
    iframe: "wms-custom-uri-frame",
  },
  toolMaster: process.env.REACT_APP_TOOLS_MASTER,
  toolMode: process.env.REACT_APP_TOOLS_MODE,
  ialtURL: process.env.REACT_APP_IALT_BASEURL,
  integrafs: process.env.REACT_APP_INTEGRAFS,
  auth: {
    base_url: process.env.REACT_APP_WSO2_BASEURL,
    client_id: process.env.REACT_APP_OAUTH_CLIENT_ID,
    uri: {
      status: "/auth/status",
      redirect_uri: "/auth/redirect",
      signout: "/auth/signout",
      authorize: "/oauth2/authorize",
      getScreensInfo: "/auth/authorization/getScreensInfo",
      getScreenInfo: "/auth/authorization/getScreenInfo",
    },
  },
};

// apiUrl.nodeApi.action.general.process

export const apiUrl = {
	camunda: {
		allTaskList: "/camunda/task/all",
		searchTask: "/camunda/task/search"
	},
	okMRoot: "/okm:root/",
	nodeApi: {
		getDynamicColumns: "/api/common/getDynamicColumns",
		getProblemTask: "/api/task/getProblemTask",
		getElsevierWF: "/api/task/getElsevierWF",
		getStandardQuery: "/api/task/getStandardQuery",
		updateDataPT: "/api/task/updateDataPT",
		getFilteredList: "/api/task/getFilteredList",
		getWIPWorkorderReport: "/api/report/getWIPWorkorderReport",
		exportWOReport: "/api/report/exportWOReport",
		getWIPChapterReport: "/api/report/getWIPChapterReport",
		getJobSummaryReport: "/api/report/getJobSummaryReport",
		getToolsMasterAccessRightsReport:
			"/api/report/getToolsMasterAccessRightsReport",
		getToolsListServerPath: "/api/report/getToolsListServerPath",
		getUsersByCustomer: "/api/report/getUsersByCustomer",
		getUsersByDeliveryUnit: "/api/report/getUsersByDeliveryUnit",
		getCustomerForTools: "/api/report/getCustomerForTools",
		postToolsMasterAccessRights: "/api/report/postToolsMasterAccessRights",
		addNewTool: "/api/report/addNewTool",
		graphicImageDelete: "/api/report/graphicimagedelete",
		toolsWIPReport: "/api/report/toolsWIPReport",
		stageListForCustomer: "/api/report/stageListForCustomer",
		getUserList: "/api/report/getUserList",
		activityListForStage: "/api/report/activityListForStage",
		getTaskList: "/api/task/getTaskList",
		getFileValidationStatus: "/api/utils/getFileValidationStatus/",
		isValidFile: "/api/utils/isValidFile/",
		isDirectFirstProof: "/api/task/isDirectFirstProof/",
		deleteFile: "/api/utils/okm/deleteFile",
		saveView: "/api/task/saveView",
		deleteView: "/api/task/deleteView",
		getFileDetails: "/api/task/getFileDetails",
		getFileDetailsNew: "/api/task/getFileDetailsNew",
		getEventIdForWo: "/api/task/getEventIdForWo",
		getToolsDetails: "/api/task/getToolsDetails",
		getToolStatus: "/api/task/getToolStatus",
		invokeTools: "/api/task/invokeTools",
		updateWoStatus: "/api/task/completeWorkorder",
		updateFileSyncStatus: "/api/task/updateFileSyncStatus",
		getPlaceHolders: "/api/task/getPlaceHolders",
		setPIIPlaceHolders: "/api/task/setPIIPlaceHolders",
		setIsRevisesValue: "/api/task/setIsRevisesValue",
		getIsRevisesValue: "/api/task/getIsRevisesValue",
		setIsRevisesReason: "/api/task/setIsRevisesReason",
		getHistory: "/api/task/getHistory",
		getViewHistory: "/api/task/getViewHistory",
		getAuditAndFile: "/api/task/getAuditAndFile",
		taskAction: "/api/task/taskAction",
		getPriorityList: "/api/task/getPriorityList",
		getCopyEditingLevel: "/api/task/getCopyEditingLevel",
		setIssueStartPage: "/api/task/setIssueStartPage",
		completeTask: "/api/task/completeTasks",
		getIncomingFileType: "/api/utils/getIncomingFileType",
		getOverallJobHistory: "/api/report/getOverallJobHistory",
		insertCoverArticle: "/api/dll/createCoverArticle",
		getAcknowledgementReport: "/api/report/getAcknowledgementReportACS",
		getNoteFromCustomerReport: "/api/report/getnotefromcustomerACS",
		getNoteFromvendorReport: "/api/report/getnotefromVendorReport",
		doNotPublishReport : "/api/report/doNotPublishReport",
		convertFilesReport : "/api/report/convertFilesReport",
		getOverallFileStatusReport: "/api/report/getOverallFileStatusReport",
		getOverallFileOptionLists: "/api/report/getOverallFileOptionLists",
		getEngineFailure: "/api/report/getEngineFailure",
		 getFTPFailure: "/api/report/getFTPFailure",
   updateFTPFailure: "/api/report/updateFTPFailure",
   getCampusaudit: "/api/report/getCampusSignalAuditReport",
		actionTypes: {
			claim: "/Claim",
			assign: "/Assign",
			priority: "/Priority",
			reject: "/Reject",
			TaskView: "/TaskView",
			calimPreProcess: "/calimPreProcess",
			TaskViewPre: "/TaskViewPreProcess"
		},
		action: {
			general: {
				process: "/api/task/action/general/process"
			},
			workflow: {
				preProcess: "/api/task/action/workflow/preprocess",
				process: "/api/task/action/workflow/process"
			}
		},
		bpmn: {
			parse: "/api/bpmn/parser/parse",
			save: "/api/bpmn/parser/save",
			updateStageInfo: "/api/bpmn/listener/updateStageInfoForSequence",
			getFileSeqDetails: "/api/bpmn/listener/getFileSeqDetails"
		},
		getUomHistory: "/api/task/getUomHistory",
		updatesStatusValueInToolsApi: "/api/task/updatesStatusValueInToolsApi",
		getWOLists: "/api/woi/getWOLists",
		WOICreation: "/api/woi/create",
		getWOStageLists: "/api/woi/getWOStageLists",
		getStageList: "/api/woi/getStageList",
		getStageHistory: "/api/woi/getStageHistory",
		checkMultiInstance: "/api/woi/checkMultiInstance",
		addFileButtonValidation: "/api/woi/addFileButtonValidation",
		getEventlog: "/api/woi/getEventlog",
		getProcessInstance: "/api/woi/getProcessInstance",
		getWOStageChapters: "/api/woi/getWOStageChapters",
		getWOStageFiles: "/api/woi/getWOStageFiles",
		getWOFTemplates: "/api/woi/getWOFTemplates",
		// fileUpload: '/api/woi/fileUpload',
		getFolderPath: "/api/utils/getFolderPath/",
		saveUploadFile: "/api/task/saveUploadFile",
		getOptionLists: "/api/woi/getOptionLists",
		checkAvailability: "/api/woi/checkAvailability",
		getWoDetails: "/api/woi/getWoDetails",
		saveChapter: "/api/woi/saveChapter",
		getIncomingData: "/api/woi/getIncomingData",
		updateFilesIncomingData: "/api/woi/updateFilesIncomingData",
		addFileGraphicImage: "/api/woi/addFileGraphicImage",
		tocFileEnableE2E: "/api/woi/tocFileEnableE2E",
		fileNameUpdate: "/api/woi/fileNameUpdate",
		updateChapter: "/api/woi/updateChapter",
		saveBookCompleted: "/api/woi/saveBookCompleted",
		deleteChapter: "/api/woi/deleteChapter",
		bookComplete: "/api/woi/bookComplete",
		exportIncomingData: "/api/woi/exportIncomingData",
		triggerWOStageWf: "/api/woi/triggerWOStageWf",
		triggerMultipleInstance: "/api/woi/triggerMultipleInstance",
		getPreviousChapterPath: "/api/woi/getPreviousChapterPath",
		getWoStageIterationPath: "/api/woi/getWoStageIterationPath",
		updateWoReport: "/api/woi/updateWoReport",
		updateWoStage: "/api/woi/updateWoStage",
		getAssigneeList: "/api/task/assigneeList",
		getFilteredWoiList: "/api/woi/getFilteredWoiList",
		getStageListById: "/api/woi/getStageListById",
		getOverDueList: "/api/woi/getOverDueList",
		getStageOverdueCount: "/api/woi/getStageOverdueCount",
		getBookComplete: "/api/woi/getBookComplete",
		getAdditionalInfo: "/api/woi/getAdditionalInfo",
		getWfTargetStageList: "/api/woi/getWfTargetStageList",
		getLocalBasePath: "/api/utils/getLocalBasePath/",

		fileRead: "/api/task/fileRead",
		reorderFile: "/api/task/reorderFile",
		reorderFileFromIncoming: "/api/task/reorderFileFromIncoming",
		updateAuditHistory: "/api/task/updateAuditHistory",
		isDownloadAndUploadFile: "/api/task/isDownloadAndUploadFile",
		isFileCheckout: "/api/task/isFileCheckout",
		newDocumentFileupload: "/api/task/newDocumentFileupload",
		newFileType: "/api/task/newFileType",
		newFileTypeUpdate: "/api/task/newFileTypeUpdate",
		updateFileE2EEnableTrn: "/api/task/updateFileE2EEnableTrn",
		defectCategoryList: "/api/task/defectCategoryList",
		fileTypeList: "/api/task/fileTypeList",
		checkFileTypeStatus: "/api/task/checkFileTypeStatus",
		getLastInstanceActivity: "/api/task/getLastInstanceActivity",
		getChecklist: "/api/task/getChecklist",
		getviewProofing: "/api/task/getviewProofing",
		checktoolLinkStatus: "/api/task/checktoolLinkStatus",
		backupFileList: "/api/utils/getBackupFileDetails",
		captureUserEvent: "/api/task/captureUserEvent",
		updateRunOnFileSequence: "/api/task/updateRunOnFileSequence",
		createOtherArticleIssue: "/api/woi/workorderCreationFromE2EAPI",
		getjournalid: "/api/task/getjournalid",
		getWOServiceList: "/api/woi/getWOServiceList",
		updateWoService: "/api/woi/updateWoService",
		deleteWoService: "/api/woi/deleteWoService",
		getActivityMasterList: "/api/master/getActivityMasterList",
		getStageMasterList: "/api/master/getStageMasterList",
		getDivisionMasterList: "/api/master/getDivisionMasterList",
		getSubDivisionMasterList: "/api/master/getSubDivisionMasterList",
		createActivity: "/api/master/createActivity",
		deleteActivity: "/api/master/deleteActivity",
		createStage: "/api/master/createStage",
		deleteStage: "/api/master/deleteStage",
		createDivision: "/api/master/createDivision",
		deleteDivision: "/api/master/deleteDivision",
		createSubDivision: "/api/master/createSubDivision",
		deleteSubDivision: "/api/master/deleteSubDivision",
		getMasterOptionLists: "/api/master/getMasterOptionLists",
		getJournalMasterOptionLists: "/api/master/getJournalMasterOptionLists",
		getNlpOptionLists: "/api/master/getNlpOptionLists",
		getJournalMasterConfig: "/api/master/getJournalMasterConfig",
		getJournalListByID: "/api/master/getJournalById",

		//Tool Master Start
		signalReceiverFromFtp: "/api/master/signalReceiverFromFtp",
		pkgUploadOpenKmToSftp: "/api/master/pkgUploadOpenKmToSftp",
		getToolsCommonOptions: "/api/master/getToolsCommonOptions",
		getToolMasterOptions: "/api/master/getToolMasterOptions",
		getSoftwareMasterOptions: "/api/master/getSoftwareMasterOptions",
		createToolMaster: "/api/master/createToolMaster",
		createComposingSoftwareMaster: "/api/master/createComposingSoftwareMaster",
		getToolMaster: "/api/master/getToolMaster",
		getSoftwareMaster: "/api/master/getSoftwareMaster",
		deleteToolMaster: "/api/master/deleteToolMaster",
		deleteSoftwareMaster: "/api/master/deleteSoftwareMaster",
		getToolById: "/api/master/getToolById",
		getSoftwareById: "/api/master/getSoftwareById",
		updateToolById: "/api/master/updateToolById",
		updateSoftwareById: "/api/master/updateSoftwareById",
		getToolstPlaceholderField: "/api/master/getToolstPlaceholderField",
		getLocalToolsPath: "/api/master/getLocalToolsPath",
		multipleInstance: "/api/master/multipleInstance",
		deletemultipleInstanceTwo: "/api/master/deletemultipleInstanceTwo",
		getWfidOptions: "/api/master/getWfidOptions",
		getToolidOptions: "/api/master/getToolidOptions",
		getSoftwareidOptions: "/api/master/getSoftwareidOptions",
		stageActivityDetails: "/api/master/stageActivityDetails",
		softstageActivityDetails: "/api/master/softstageActivityDetails",
		wipActivityDetails: "/api/master/wipActivityDetails",
		retriggerActivity: "/api/master/retriggerActivity",
		workorderlock: "/api/master/workorderlock",
		//Tool Master End

		//Configuration Ftp Start
		getFtpList: "/api/master/getFtpList",

		//Configuration Ftp End

		//Library Repository Start
		getTemplateById: "/api/master/getTemplateById",
		addTempDetails: "/api/master/addTempDetails",
		getTemplateCommonOptions: "/api/master/getTemplateCommonOptions",
		getLibraryTempList: "/api/master/getLibraryTempList",
		getSeparateTempList: "/api/master/getSeparateTempList",
		getFileInfo: "/api/master/getFileInfo",

		//Library Repository End

		//NLP Master Start
		getNLPMasterData: "/api/master/getNLPMasterData",
		getNLPScoreData: "/api/master/getNLPScoreData",
		saveLanguageVariant: "/api/master/saveLanguageVariant",
		deleteLanguageVariant: "/api/master/deleteLanguageVariant",
		saveNlpScoreWiseActivity: "/api/master/saveNlpScoreWiseActivity",
		deleteNlpScoreWiseActivity: "/api/master/deleteNlpScoreWiseActivity",

		//NLP Master End

		createNormMaster: "/api/master/createNormMaster",
		updateNorms: "/api/master/updateNorms",
		checkJobNormCombination: "/api/master/checkJobNormCombination",
		getNormById: "/api/master/getNormById",
		getNormMaster: "/api/master/getNormMaster",
		deleteNormMaster: "/api/master/deleteNormMaster",
		createJournalMaster: "/api/master/createJournalMaster",
		createNewJournalMaster: "/api/master/createNewJournalMaster",
		updateNewJournalMaster: "/api/master/updateNewJournalMaster",
		updateJournalMaster: "/api/master/updateJournalMaster",
		journalFile: "/api/master/journalFile",
		getJournalList: "/api/master/getJournalList",
		nonArticleList: "/api/master/nonArticleList",
		getjournalduedays: "/api/master/getjournalduedays",
		getJournalInstruction: "/api/master/getJournalInstruction",
		getJournalContact: "/api/master/getJournalContact",
		getJournalAcroymn: "/api/master/getJournalAcroymn",
		getLocationMasterList: "/api/master/getLocationMasterList",
		createLocation: "/api/master/createLocation",
		deleteLocation: "/api/master/deleteLocation",
		getColorMasterList: "/api/master/getColorMasterList",
		createColor: "/api/master/createColor",
		deleteColor: "/api/master/deleteColor",
		getSoftwareMasterList: "/api/master/getSoftwareMasterList",
		createSoftware: "/api/master/createSoftware",
		deleteSoftware: "/api/master/deleteSoftware",
		filesStatusReport: "/api/task/getFilesStatus",
		fileStatusReport: "/api/task/getFileStatus",
	    getToolsStatusDetails : "/api/task/getToolsStatusDetails",
		getFileDetailsforWorkorder: "/api/master/getFileDetailsforWorkorder",
		saveWFStage: "/api/config/saveWFStage",
		saveWFActivity: "/api/config/saveWFActivity",
		listFolderContents: "/api/master/listFolderContents",
		getBlobFileDetailsForPath: "/api/master/getBlobFileDetailsForPath",
		deleteFilePathTrn: "/api/master/deleteFilePathTrn",
		blobFilesActionsAudit: "/api/master/blobFilesActionsAudit",
		ActivityConfigDetails: "/api/config/ActivityConfigDetails",
		ToolsConfigDetails: "/api/config/ToolsConfigDetails",
		updateForActConfig: "/api/config/updateForActConfig",

		softwareDetails: "/api/config/softwareDetails",
		softwareIOList: "/api/config/softwareIOList",
		toolDetails: "/api/config/toolDetails",
		toolParamsSuggestions: "/api/config/toolParamsSuggestions",
		OptionList: "/api/config/OptionList",
		getWFStageDetails: "/api/config/getWFStageDetails",
		getWFActivityDetails: "/api/config/getWFActivityDetails",

		getAllMasterStages: "/api/config/getAllMasterStages",
		getStageOrder: "/api/config/getStageOrder",
		saveStageOrder: "/api/config/saveStageOrder",

		getAllMasterActivities: "/api/config/getAllMasterActivities",
		getStageSpecificActivities: "/api/config/getStageSpecificActivities",
		getStageSpecificMultiActivities:
			"/api/config/getStageSpecificMultiActivities",
		saveActivityOrder: "/api/config/saveActivityOrder",

		getWorkorderWithNameLike: "/api/master/getWorkorderWithNameLike",

		getFilenameSuggestions: "/api/config/getFilenameSuggestions",
		getExistingFiles: "/api/config/getExistingFiles",
		getRejectFiles: "/api/config/getRejectFiles",
		getWfFilename: "/api/config/getWfFilename",
		getFileTransferList: "/api/config/getFileTransferList",
		deleteFileTransferList: "/api/config/deleteFileTransferList",
		toolIOList: "/api/config/toolIOList",
		toolsIOAdd: "/api/config/toolsIOAdd",
		softwareIOAdd: "/api/config/softwareIOAdd",

		getAccessRightsBlobFiles: "/api/master/getAccessRightsBlobFiles",
		getJournalBaseWOList: "/api/master/getJournalBaseWOList",
		getJournalOptionList: "/api/master/getJournalOptionList",
		getWoChapters: "/api/master/getWoChapters",
		getToolsList: "/api/config/getToolsList",
		getUserMapDU: "/api/config/getUserMapDU",
		updateUserMapDU: "/api/config/updateUserMapDU",

		userList: "/api/master/userList",
		userOption: "/api/master/OptionList",
		userRoleList: "/api/master/userRoleList",
		createUser: "/api/master/createUser",
		createRole: "/api/master/createRole",
		createSkill: "/api/master/createSkill",
		deleteSkill: "/api/master/deleteSkill",
		getTemplateList: "/api/master/getTemplateList",

		addTemplateDetails: "/api/master/addTemplateDetails",
		updateTemplateStatus: "/api/master/updateTemplateStatus",
		deleteTemplate: "/api/master/deleteTemplate",
		getTemplatePath: "/api/utils/getTemplatePath",

		getToolsOptionList: "/tools/status/getToolsOptionList",

		getNotificationsOptionList: "/api/master/getNotificationsOptionList",

		getChecklistOptionList: "/api/master/getChecklistOptionList",
		createCheckListMaster: "/api/master/createCheckListMaster",
		getCheckListMaster: "/api/master/getCheckListMaster",
		getPrePopulateInstruction: "/api/master/getPrePopulateInstruction",
		getPrePopulateInstructionAnswers:
			"/api/master/getPrePopulateInstructionAnswers",
		updateCheckListMaster: "/api/master/updateCheckListMaster",
		deleteCheckListMaster: "/api/master/deleteCheckListMaster",
		checkSkillAvaliablity: "/api/master/checkSkillAvaliablity",
		getBookFields: "/api/master/getBookFields",
		getAllBookFields: "/api/master/getAllBookFields",
		saveFieldOrder: "/api/master/saveFieldOrder",
		addBookField: "/api/master/addBookField",
		deleteBookField: "/api/master/deleteBookField",
		deleteMappedBookField: "/api/master/deleteMappedBookField",
		updateBookField: "/api/master/updateBookField",
		updateBookFieldForCustomer: "/api/master/updateBookFieldForCustomer",
		getCustomers: "/api/master/getActiveCustomers",
		getCustomerslist: "/api/master/getActiveCustomersList",
		getJournals: "/api/master/journals",
		getStages: "/api/master/stages",
		getVolumes: "/api/master/volumes",
		getActivities: "/api/master/activities",
		getWorkOrders: "/api/master/workorders",
		getTableData: "/api/master/getProductionTableData",
		logJobConfigAudit: "/api/master/logJobConfigAudit",
		updateStatus: "/api/master/updateStatus",

		getWorkflowLists: "/api/workflow/getWorkflowLists",
		getPageCount: "/api/fileDetails/getPageCount",
		getUomList: "/api/uom/getUomList",
		updateUomList: "/api/uom/updateUomList",
		readOrderDateFromEmail: "/api/woi/readOrderDateFromEmail",

		getCustomerList: "/api/workflow/getCustomerLists",
		getAllStageList: "/api/workflow/getAllStageList", // added for workflow screen mapping  (Masterworkflow screen)
		updateWfDefTable: "/api/workflow/updateWfDefTable", //added for workflow screen mapping  (Masterworkflow screen)
		getIncomingFlowList: "/api/workflow/getIncomingFlowList", //added for workflow screen mapping (Masterworkflow screen)
		getSequenceList: "/api/workflow/getSequenceList", //added for workflow screen mapping (Masterworkflow screen)
		getWfDefDetails: "/api/workflow/getWfDefDetails", //added for workflow screen mapping (Masterworkflow screen)
		addWfdefEntries: "/api/workflow/addWfdefEntries", //added for workflow screen mapping (Masterworkflow screen)
		deleteWfDefTable: "/api/workflow/deleteWfDefTable", //added for workflow screen mapping (Masterworkflow screen)

		graphicArt: "/api/woi/graphicArt",
		getGraphicLists: "/api/woi/getGraphicLists",
		getConnectionParameter_Springer: "/api/woi/getConnectionParameter_Springer",
		graphicArtAuditLists: "/api/woi/getGraphicAuditLists",
		woInstructions: "/api/woi/woInstructions",
		woInstructionFiles: "/api/woi/woInstructionFiles",
		getWOI: "/api/woi/getWOI",
		editWOI: "/api/woi/editWOI",
		deleteWOI: "/api/woi/deleteWOI",

		validateUserTask: "/api/task/validateUserTask",
		getWIPReport: "/api/report/getwipreport",
		getWIPReportTwo: "/api/report/getWIPReportTwo",
		getStageCreatedCount: "/api/report/getStageCreatedCount",
		getWipEngineActivityReport: "/api/report/getWipEngineActivityReport",
		getToolsMasterAccessRights: "/api/report/getToolsMasterAccessRights",
		getDespatchFailureReport: "/api/report/getDespatchFailureReport",
		getFTPAuditReport: "/api/report/getFTPAuditReport",
		getFTPDownloadReportSpringer: "/api/report/getFTPDownloadReportSpringer",
		getDownloadUploadManuscriptReport:
			"/api/report/getDownloadUploadManuscriptReport",
		getJobsheetHistoryforSpringer: "/api/report/getJobsheetHistoryforSpringer",
		getFilepathforSpringer: "/api/report/getFilepathforSpringer",
		getZipFileDetailOnId: "/api/woi/getZipFileDetailOnId",
		updateRetryCountInDatabase: "/api/woi/updateRetryCountInDatabase",
		getAuditReport: "/api/report/getAuditReport",
		getCompletedWorkOrders: "/api/report/getCompletedWorkOrders",
		getFTPDownloadReportACS: "/api/report/getFTPDownloadReportACS",
		getPBTaskData: "/api/report/getPBTaskData",
		getElsBasePath: "/api/report/getElsBasePath",
		getCopyeditingQueACS: "/api/report/getCopyeditingQueACS",
		getFilepathforACS: "/api/report/getFilepathforACS",
		// getWipEngineActivityReport: "/api/report/getWipEngineActivityReport",
		// getToolsMasterAccessRights: "/api/report/getToolsMasterAccessRights",
		// getDespatchFailureReport: "/api/report/getDespatchFailureReport",
		// getFTPAuditReport: "/api/report/getFTPAuditReport",
		// getFTPDownloadReportSpringer: "/api/report/getFTPDownloadReportSpringer",
		// getAuditReport: "/api/report/getAuditReport",
		// getCompletedWorkOrders: "/api/report/getCompletedWorkOrders",
		getWIPDetailedReport: "/api/report/getWIPDetailedReport",
		remainingChaptersCount: "/api/woi/remainingChaptersCount",
		getTemplateListOptions: "/api/woi/getTemplateListOptions",
		updateCamundaDetails: "/api/woi/updateCamundaDetails",
		getEnableListener: "/api/woi/getEnableListener",
		updateTemplateList: "/api/woi/updateTemplateList",
		getSelectedTemplate: "/api/woi/getSelectedTemplate",
		templateList: "/api/woi/templateList",
		getProductivityReport: "/api/report/getProductivityReport",
		getReportOptionLists: "/api/report/getReportOptionLists",
		getQualityReport: "/api/report/getQualityReport",
		getQualityReportOptionLists: "/api/report/getQualityReportOptionLists",
		getExternalCustomerContacts: "/api/woi/getExternalCustomerContacts",
		getArticleIssueList: "/api/woi/getArticleIssueList",
		getArticleIssueListCombined: "/api/woi/getArticleIssueListCombined",
		getMonitoringReport: "/api/report/getMonitoringReport",
		getMonitoringReportOptionList: "/api/report/getMonitoringReportOptionList",
		saveAssignedArticle: "/api/woi/saveAssignedArticle",
		getAssignedArticleList: "/api/woi/getAssignedArticleList",
		getAssignedArticleListCombined: "/api/woi/getAssignedArticleListCombined",
		deleteAssignedArticle: "/api/woi/deleteAssignedArticle",
		copyArticleToIssue: "/api/woi/copyArticleToIssue",
		getArticleStatus: "/api/woi/getArticleStatus",
		getQueryBuilderOptions: "/api/woi/getQueryBuilderOptions",
		getJobNormOptionList: "/api/woi/getJobNormOptionList",
		getQueryHistory: "/api/woi/getQueryHistory",
		postReply: "/api/woi/postReply",
		queryInsertion: "/api/woi/queryInsertion",
		queryFile: "/api/woi/queryFile",
		getQueryList: "/api/woi/getQueryList",
		getGraphicsQueries: "/api/woi/getgraphicsqueries",
		postGraphicsQueries: "/api/woi/postgraphicsqueries",
		getQueryListforDespatch: "/api/woi/getQueryListforDespatch",
		getLastActivityForQueryCheck: "/api/woi/getLastActivityForQueryCheck",
		getAdditionalOptionList: "/api/woi/getAdditionalOptionList",
		createAdditionalInfoList: "/api/woi/createAdditionalInfoList",
		updateAdditionalInfoList: "/api/woi/updateAdditionalInfoList",
		getWorksheetId: "/api/woi/getWorksheetId",
		getProofingType: "/api/woi/getProofingType",

		//graphics stage image upload
		getGraphicsTrnImages: "/api/woi/getTrnImages",
		getSupplimentFilesList: "/api/woi/getSupplimentFilesList",
		deleteSupplimentFiles:"/api/woi/deleteSupplimentFiles",
		updateImagepathtrn: "/api/woi/updateImagepathtrn",
		deleteImagepathtrn: "/api/woi/deleteImagepathtrn",
		graphicsImageActions: "/api/woi/graphicsImageActions",
		toolsUploadActions: "/api/woi/toolsUploadActions",
		getFormattedName: "/api/woi/getFormattedName",
		listAllFiles: "/api/fileDetails/listAllFiles",
		getiTracksReset: "/api/task/productionReset",
		updateBookDetailsForActivites: "/api/woi/updateBookDetailsForActivites",
		getIncomingDetailsIdList: "/api/woi/getIncomingDetailsIdList",
		updateIncomingCountValue: "/api/woi/updateIncomingCountValue",
		getFromattedGraphicPath: "/api/custom-uri/getFormattedGraphicPath",
		getToolsRunningStatus: "/api/task/getToolsRunningStatus",
		getIsUpdatedPackageReq: "/api/task/getIsUpdatedPackageReq",
		getPreviousActivityRemarks: "/api/task/getPreviousActivityRemarks",
		getQualityRemarks: "/api/report/getqualityremarks",
		getWorkflowName: "/api/woi/getWorkflowName",
		insertWipStageNotes: "/api/report/insertWipStageNotes",
		getimcomingDetails: "/api/woi/getimcomingDetails",

		getConvertionFilesList: "/api/woi/getConvertionFilesList",
		createConvertionFilesLog: "/api/woi/createConvertionFilesLog",

		emailTrigger: "/api/aduit/emailTrigger",
		trackitTrigger: "/api/aduit/trackitTrigger",
		woJobNormsMapping: "/api/woi/woJobNormsMapping",
		getWOJobNormsMappedList: "/api/woi/getWOJobNormsMappedList",
		deleteWOJobnormsMap: "/api/woi/deleteWOJobnormsMap",
		downloadManuscript: "/api/report/getdownloadmanuscript",
		getswiftxmlreport: "/api/report/getswiftxmlreport",
		pkgUploadToSftp: "/api/woi/pkgUploadToSftp",
		getlicensechaserreport: "/api/report/getlicensechaserreport",
		createManualBooking: "/api/utils/tools/createManualBooking",
		downloadManuscriptfile: "/api/report/getdownloadManuscriptfile",
		getManuscriptStatus: "/api/report/getManuscriptStatus",
		activityTrackList: "/api/report/activityTrackList",
		activityInterval: "/api/report/getactivitystartend",
		ftpjobretrigger: "/api/report/ftpjobretrigger",

		getNotificationOptions: "/api/notification/getNotificationOptions",
		createNotificationSender: "/api/notification/createNotificationSender",
		updateNotificationSender: "/api/notification/updateNotificationSender",
		getNotificationSenderList: "/api/notification/getNotificationSenderList",
		deleteNotificationSenderMap:
			"/api/notification/deleteNotificationSenderMap",
		createNotification: "/api/notification/createNotification",
		getNotificationList: "/api/notification/getNotificationList",
		getNotificationDetailList: "/api/notification/getNotificationDetailList",
		updateNotification: "/api/notification/updateNotification",
		deleteNotification: "/api/notification/deleteNotification",
		getWOListById: "/api/woi/getWOListById",
		getFilteredWorkorder: "/api/woi/getFilteredWorkorder",
		getFilteredJournal: "/api/woi/getFilteredJournal",
		getUserOpenTask: "/api/task/getUserOpenTask",

		getWoStageActivityCompletedList: "/api/woi/getWoStageActivityCompletedList",
		resetModification: "/api/task/resetModification",
		resetModificationWithoutCamunda: "/api/task/resetModificationWithoutCamunda",
		getWipActivityList: "/api/woi/getWipActivityList",
		getWOSourceFileDetails: "/api/woi/getWOSourceFileDetails",
		checkAllTaskCompletionReset: "/api/task/checkAllTaskCompletionReset",
		getUnActiveSupplimentary:"/api/task/getUnActiveSupplimentary",
		uploadFileCreateAndUpdate: "/api/fileDetails/uploadFileCreateAndUpdate",

		// file upload in azure
		fileUpload: "/api/fileDetails/fileUpload",
		fileDelete: "/api/fileDetails/fileDelete",
		fileDownload: "/api/fileDetails/fileDownload",
		localFileGetDownload: "/api/fileDetails/localFileGetDownload",
		filedonwloadLocal: "/api/fileDetails/filedonwloadLocal",
		localfileDownload: "/api/fileDetails/localfileDownload",
		getIssueWorkorderInfo: "/api/custom-uri/getIssueWorkorderInfo",
		getLogin: "/auth/authenticate",
		updateDU: "/auth/setuserdu",
		fetchguId: "/api/task/fetchguId",
		fetchCorrection: "/api/task/fetchCorrection",
		insertCorrectionDetails: "/api/task/insertCorrectionDetails",
		insertNotesToACS: "/api/task/notestoacs",
		getNotesACS: "/api/task/getnotesacs",
		insertDNPACS: "/api/task/dnpacs",
		acsWorkingPath: "/api/task/acsworkingpath",
		addpbData: "/api/task/addpbData",
		getpbData: "/api/task/getpbData",
		getElsevierCustomerStageName: "/api/task/getElsevierCustomerStageName",
		getSprBookFileSequence: "/api/task/getFileSequence",
		updateFileSequence: "/api/task/updateFileSequence",
		//cutomer config details
		getcutomerconfigdetails: "/api/master/getcustomerconfigdetails",
		getDeliverUnitList: "/api/master/getDeliverUnitList",
		saveActivityMapping: "/api/config/saveActivityMapping",
		getBookMasterFieldsConfig: "/api/master/getBookMasterFieldsConfig",
		bookmasterInsert: "/api/master/bookmasterInsert",
		bookmasterUpdate: "/api/master/bookmasterUpdate",
		getChapterMaster: "/api/master/getChapterMaster",
		sendS200IntroMail: "/api/sprbooks/sendS200IntroMail",
		updateChapterMaster: "/api/master/updateChapterMaster",
		getbookMasterRecords: "/api/master/getbookMasterRecords",
		getbookdetailforid: "/api/master/getbookdetailforid",
		getMasterMenu: "/api/master/getMasterMenu",
		getScreenMaster: "/api/master/getScreenMaster",
		getEntityMaster: "/api/master/getEntityMaster",
		getScreenmappingMaster: "/api/master/getScreenmappingMaster",
		getRoleMappingMaster: "/api/master/getRoleMappingMaster",
		getDropdownMaster: "/api/master/getDropdownMaster/",
		addMenuMaster: "/api/master/addMenuMaster",
		updateMenuMaster: "/api/master/updateMenuMaster",
		addScreenMaster: "/api/master/addScreenMaster",
		updateScreenMaster: "/api/master/updateScreenMaster",
		addEntityMaster: "/api/master/addEntityMaster",
		updateEntityMaster: "/api/master/updateEntityMaster",
		addScreenMapping: "/api/master/addScreenMapping",
		updateScreenMapping: "/api/master/updateScreenMapping",
		addRoleMapping: "/api/master/addRoleMapping",
		updateRoleMapping: "/api/master/updateRoleMapping",
		getAllWorkflowConfig: "/api/task/getAllWorkflowConfig",
		checkPBTaskaccess: "/api/task/checkPBTaskaccess",
		extractFileConfig: "/api/custom-uri/extractFileConfig",
		getMultiFilesStatusReport: "/api/task/getMultiFilesStatusReport",
		getToolRunningStatus: "/api/task/getToolRunningStatus",
		getFromOptions: "/api/master/fromFieldDropdown",
		getToOptions: "/api/master/toFieldDropdown",
		getCcOptions: "/api/master/ccFieldDropdown",
		getBccOptions: "/api/master/bccFieldDropdown",
		editEmailTemplate: "/api/master/editEmailTemplate/:id",
		getAllEmailTemplate: "/api/master/getAllEmailTemplate",
		createEmailTemplate: "/api/master/createEmailTemplate",
		updateEmailTemplate: "/api/master/updateEmailTemplate/:id",
		getXMLtrackerReportACS: "/api/report/getXMLtrackerReportACS",
		triggerWithoutCamundaWorkflow: "/api/woi/triggerWithoutCamundaWorkflow",
		getBasePath: "/api/task/getBasePath",
		getXmlReportUrl: "/api/task/getXmlReportUrl",
		getJournalSignalAudit: "/api/signal/getJournalSignalAudit",
		getJournalSignalHistory: "/api/signal/getJournalSignalHistory",
		getCAMSAcknowledge: "/api/report/getCAMSAcknowledge",
		insertCAMSAcknowledge: "/api/report/insertCAMSAcknowledge",
		camsAcknowledgeNotification: "/api/woi/camsAcknowledgeNotification",
		getshiftwiseinflowreport: "/api/report/getshiftwiseinflowreport",
		getshiftwiseinoutreportmaster: "/api/report/getshiftwiseinoutreportmaster",
		getshiftwiseoutflowreport: "/api/report/getshiftwiseoutflowreport",
		getoutflowpivotreport: "/api/report/getoutflowpivotreport",

		getArticlePII:"/api/woi/getArticlePII",
		sendCampusSignal:"/api/woi/sendCampusSignal",
		autoStageTriggerWithoutCamunda:"/api/woi/autoStageTriggerWithoutCamunda",
		getStageActivityStatus:"/api/woi/getStageActivityStatus",
		getCAMPUSSignalOptions:"/api/woi/getCAMPUSSignalOptions",
		toConstructSignalPayload:"/api/woi/toConstructSignalPayload",
		getIsUpdatedCampusXML:"/api/woi/getIsUpdatedCampusXML",
		checkWO_StageExists: "/api/woi/checkWO_StageExists",
		getSignalHistory:"/api/woi/getSignalHistory",
	},
	javaApi: {
		base_url: process.env.REACT_APP_OKM_BASEURL,
		uri: {
			upload: "/upload",
			multiUpload: "/multifileuploadwithpaths",
			download: "/downloaddocument/",
			viewFile: "/viewdocument/",
			checkin: "/checkin",
			downloadwithCheckout: "/downloadwithCheckout",
			multifileupload: "/multifileupload",
			forceCancelCheckout: "/forceCancelCheckout",
			delete: "/delete/",
			checkInDocumentNode: "/checkInDocumentNode",
			uploadFileNode: "/uploadFileNode"
		}
	},

	blob_rest: {
		base_url: process.env.REACT_APP_BLOB_BASEURL,
		uri: {
			upload: "document/checkin",
			delete: "document/delete",
			checkin: "document/checkin",
			checkout: "document/checkout",
			copy: "document/extendedCopy",
			download: "document/download",
			retreiveBlobFiles: "document/retreiveBlobFiles",
			getProperties: "document/getProperties",
			// localupload: 'document/localcheckin',
			// localdelete: 'document/localfiledelete',
			// localcheckin: 'document/localcheckin',
			// localcheckout: 'document/localcheckout',
			// localcopy: 'document/localextendedCopy',
			localdownload: "document/localdownload",
			localfoldercopy: "document/localfolderextendedCopy",
			localfolderzipupload: "document/localfolderzipupload",

			// retreiveLocalFiles: 'document/retreivelocalFiles',
			// getlocalProperties: 'document/getlocalProperties',
			ZIPDownloadBlobFolder: "document/ZIPDownloadBlobFolder?docPath=",
			iAltZIPDownloadBlobFolder: "document/iAltZIPDownloadBlobFolder?docPath=",
			getFileContentFromServer:"document/getlocalfilecontent"

		}
	},
	//local
	local_rest: {
		base_url: process.env.REACT_APP_LOCAL_BASEURL,
		uri: {
			localupload: "document/localcheckin",
			localdelete: "document/localfiledelete",
			localcheckin: "document/localcheckin",
			localcheckout: "document/localcheckout",
			localcopy: "document/localextendedCopy",
			localdownload: "document/localdownload",
			retreiveLocalFiles: "document/retreivelocalFiles",
			getlocalProperties: "document/getlocalProperties",
			ZIPDownloadLocalFolder: "document/ZIPDownloadLocalFolder?docPath="
		}
	},
	// new_itracks
	iTracks_rest: {
		uploadFile: "/api/itrack/fileupload",
		apiProxy: "/api/itrack/api/proxy",
		getSASurl: "/api/itrack/download/",
		// apiProxy:"/api/proxy",
		iproductivity: {
			getiProdAzureFolderPath: "/api/itrack/iproductivity/folderpath",
			getMasters: "/api/itrack/iproductivity/masters/",
			getDynamicColumns: "/api/itrack/iproductivity/dynamicColumns",
			getCustInfo: "/api/itrack/iproductivity/get/customerinfo",
			getCustomerDetails: "/api/itrack/iproductivity/customerinfo/",
			getCustNorms: "/api/itrack/iproductivity/norms/",
			getNormsActidSkid: "/api/itrack/iproductivity/getnorms",
			copyNorm: "/api/itrack/iproductivity/copynorm",
			copyActivity: "/api/itrack/iproductivity/copyactivity",
			createActivityNorms: "/api/itrack/iproductivity/norms",
			getCustActivity: "/api/itrack/iproductivity/norms/activity/",
			getSubDU: "/api/itrack/iproductivity/masters/subdiv/",
			getMastersIteration: "/api/itrack/iproductivity/masters/iteration",
			createCustomerNorms: "/api/itrack/iproductivity/customerinfo",
			createCustomerMst: "/api/itrack/iproductivity/createcustomer",
			deleteCustInfo: "/api/itrack/iproductivity/deletecustinfo",
			deleteNormsInfo: "/api/itrack/iproductivity/deletenorms",
			viewNormsVersionInfo: "/api/itrack/iproductivity/normsversion",
			logistics: "/api/itrack/iproductivity/logistics",
			getWOMasters: "/api/itrack/iproductivity/woDropDown",
			getReport: "/api/itrack/iproductivity/report",
			updateCustomerName: "/api/itrack/iproductivity/updateCustomername",
			getWorkFlow: "/api/itrack/iproductivity/getworkflow",
			getStage: "/api/itrack/iproductivity/getstage",
			getActivityByWFidStageId:
				"/api/itrack/iproductivity/getactivitybywfstage",
			getUOMDetails: "/api/itrack/iproductivity/getuomarticletitle",
			getProductivityTotal: "/api/itrack/iproductivity/getProductivityTotal",
			individualProductivityReport:
				"/api/itrack/iproductivity/individualproductivityreport",
			getReportMaster: "/api/itrack/iproductivity/getreportmaster",
			getnormsDropdown: "/api/itrack/iproductivity/getnormsdropdown",
			getJobNorms : "/api/itrack/iproductivity/getjobnorms",
			insertJobnorms : "/api/itrack/iproductivity/insertjobnorms",
			updateJobnorms : "/api/itrack/iproductivity/updatejobnorms",
			getWorkorderDetailsNorms : "/api/itrack/iproductivity/getworkorderDetailsNorms",
			validateJobNorms : "/api/itrack/iproductivity/validatejobnorms",
			getproductivityQty : "/api/itrack/iproductivity/getproductivityquantity",
			updateRemQty : "/api/itrack/iproductivity/updateremaingqty",
		},
		iquality: {
			getiQualityAzureFolderPath: "/api/itrack/iquality/folderpath",
			getCurrency: "/api/itrack/iquality/getcurrency",
			getDUandSearch: "/api/itrack/iquality/",
			getCustomer: "/api/itrack/iquality/customer/",
			getSearchforFeedback: "/api/itrack/iquality/search",
			createFeedback: "/api/itrack/iquality/feedback",
			getCCADetails: "/api/itrack/iquality/getccadetails/",
			ModifyCCA: "/api/itrack/iquality/modifyCCA",
			getD1Employee: "/api/itrack/iquality/d1/",
			getDUEmployee: "/api/itrack/iquality/d1appreciation/",
			getD1Team: "/api/itrack/iquality/d1/team/",
			createD1Team: "/api/itrack/iquality/d1",
			searchPositive: "/api/itrack/iquality/searchApprPositive",
			viewNegativeFeedback: "/api/itrack/iquality/viewfeedback",
			ActiveIPSwitchURL: "/api/itrack/iquality/existing",
			getD2details: "/api/itrack/iquality/d2/",
			createD2: "/api/itrack/iquality/d2/createD2",
			getJobcount: "/api/itrack/iquality/d2/getJobcount/",
			getJobcountdetail: "/api/itrack/iquality/d2/getJobcountdetail/",
			createD3: "/api/itrack/iquality/d3create",
			getd3details: "/api/itrack/iquality/getd3details/",
			getApprDetails: "/api/itrack/iquality/getApprdetails/",
			getDuMappingDetails: "/api/itrack/iquality/viewDUMapping",
			duMapping: "/api/itrack/iquality/FeedbackDUMapping",
			removeDivisionMapping: "/api/itrack/iquality/removeDivisionMapping/",
			// ActiveIPSwitchURL:"/iquality/existing"

			getApprDUdetails: "/api/itrack/iquality/getApprDUdetails/",
			ApprInsertDUMapping: "/api/itrack/iquality/ApprInsertDUMapping",
			ApprUpdateDUMapping: "/api/itrack/iquality/ApprUpdateDUMapping",
			ApprAwardEligibility: "/api/itrack/iquality/getAwardEligibility  ",
			ApprAwardEligibilityDetails: "/api/itrack/iquality/getApprAwardDetails/",
			deleteApprEmployeeMapping:
				"/api/itrack/iquality/deleteApprEmployeeMapping/",
			UpdateApprApprovalValues: "/api/itrack/iquality/UpdateApprApprovalValues",

			// getApprEmpMapping: "/iquality/getApprEmpMapping/",
			// ApprUpdateEmpMapping: "/iquality/ApprUpdateEmpMapping",
			// getApprAwardDetails: "/iquality/getApprAwardDetails/",
			// UpdateApprRecommandDetails: "/iquality/UpdateApprRecommandDetails",
			getsvnDID: "/api/itrack/iquality/svndID/",
			getAction: "/api/itrack/iquality/d5/actions",
			getRouteCauses: "/api/itrack/iquality/d5/routecause/",
			getD5Data: "/api/itrack/iquality/d5/getd5data/",
			InsertorUpdateD5: "/api/itrack/iquality/d5/insertorupdated5",
			DeleteD5: "/api/itrack/iquality/d5/deleted5",
			ReopenD5: "/api/itrack/iquality/d5/reopend5",
			// d4
			getD4AColumns: "/api/itrack/iquality/d4a/columns",
			getD4Adetails: "/api/itrack/iquality/d4a/details/",
			getD4ACategory: "/api/itrack/iquality/d4a/why/category",
			createD4ADetail: "/api/itrack/iquality/d4a/details",
			createD4AWhy: "/api/itrack/iquality/d4a/why",
			getD4Whys: "/api/itrack/iquality/d4a/why/",
			getD4AEmpDetail: "/api/itrack/iquality/d4a/",
			createD4Aemp: "/api/itrack/iquality/d4a/why/emp",
			getD4BDetails: "/api/itrack/iquality/d4b/",
			deleteD4BCauseDetail: "/api/itrack/iquality/d4b/delete/",

			UpdateD5Hds: "/api/itrack/iquality/d5/hdsupdate",
			D6aGetrootCauses: "/api/itrack/iquality/getRootCause",
			getDUErrorStatus: "/api/itrack/iquality/getDUErrorStatus/",
			InsertD6: "/api/itrack/iquality/d6/insertd6",
			get6dData: "/api/itrack/iquality/get6dData",
			getD7Details: "/api/itrack/iquality/d7/getd7data/",
			getD7DropdownDetails: "/api/itrack/iquality/d7/itemdropdown",
			createD7Details: "/api/itrack/iquality/d7/createD7",
			getD5Status: "/api/itrack/iquality/getD5Status/",
			getSeverity: "/api/itrack/iquality/getSeverity",
			getSeverityData: "/api/itrack/iquality/getSeveritydata/",
			InsertComplaintSeverity: "/api/itrack/iquality/insertSeverity",
			DeleteComplaintSeverity: "/api/itrack/iquality/deleteSeverity",
			getResourceType: "/api/itrack/iquality/getResourceType",
			getChargeBackData: "/api/itrack/iquality/getChargeBackData/",
			InsertChargeBack: "/api/itrack/iquality/InsertChargeBack",
			closeFeedback: "/api/itrack/iquality/d7/closeFeedback",
			getInitialSeveritydata: "/api/itrack/iquality/getInitialSeveritydata/",
			InsertAttChargeBack: "/api/itrack/iquality/InsertAttChargeBack",
			getChargeBackAttachment: "/api/itrack/iquality/getChargeBackAttachment/",
			getEscLevel: "/api/itrack/iquality/d2/getEscLevel/",
			SaveEscLevel: "/api/itrack/iquality/d2/SaveEscLevel",
			//report
			reportEmpType: "/api/itrack/iquality/report/empType",
			reportDu: "/api/itrack/iquality/report/du/",
			reportEmp: "/api/itrack/iquality/report/emp/",
			reportData: "/api/itrack/iquality/report",
			//dashboard
			getFBCountbyEmp: "/api/itrack/iquality/dashboard/getFeedbackCount/",
			getCCANotAttached: "/api/itrack/iquality/dashboard/getCCANotAttached/",
			getActionAssigned: "/api/itrack/iquality/dashboard/getFBActionassigned/",
			getComplaintsteamMember:
				"/api/itrack/iquality/dashboard/getComplaintsteamMember/",
			getResponsibleFB: "/api/itrack/iquality/dashboard/getResponsibleFB/",
			getResponsibleAppreciation:
				"/api/itrack/iquality/dashboard/getResponsibleAppreciation/",
			getActionAssignedDetails:
				"/api/itrack/iquality/dashboard/getAssignedDetails/",
			getCompaintsTeamMemberDet:
				"/api/itrack/iquality/dashboard/getCompaintsTeamMemberDet/",
			//Appreciation Report
			ApprFeedbackType: "/api/itrack/iquality/appreport/getFeedbacktype",
			getApprReportData: "/api/itrack/iquality/appreport/getApprReportData",
			getDuDetailsView: "/api/itrack/iquality/ViewToDU/",
			getEmpDataforApprreport: "/api/itrack/iquality/Apprreport/emp/",
			// delete file from table
			removeFileTbl: "/api/itrack/iquality/removefile",
			oldWMS: "/api/itrack/iquality/oldWMS",
			getD1toD7Flow: "/api/itrack/iquality/getD1toD7Flow/",
			//D2 attachment with comment
			updateattachmentcomment: "/api/itrack/iquality/d2/updateAttachComment",
			updateMIS: "/api/itrack/iquality/accountMIS",
			getApprDropdown: "/api/itrack/iquality/getApprDropdown",
			searchAppreciationFilter: "/api/itrack/iquality/searchAppreciationFilter",
			getFeedbackDropdown: "/api/itrack/iquality/getFeedbackDropdown",
			searchFeedbackFilter: "/api/itrack/iquality/searchFeedbackFilter",
			//get base du for FromDU and ToDU in ICA Others option
			getFromDUforUser: "/api/itrack/iquality/getFromDUforUser/",
			getDUFeedbackDropdown: "/api/itrack/iquality/getDUFeedbackDropdown",
			//get DU dropdown details for D2 screen
			getDUforD2: "/api/itrack/iquality/getDUforD2/",
			updateLineitem: "/api/itrack/iquality/updateLineItem",
			//report
			MisReport: "/api/itrack/iquality/misreport/",
			SaveCheckforMisReport: "/api/itrack/iquality/UpdateZeroRepeatError",
			PdfDownload: "/api/itrack/iquality/PdfDownload",
			CustomerCopy: "/api/itrack/iquality/CustomerCopy/",
			//get du for oldwms
			OldWMSDU: "/api/itrack/iquality/duforOldWMS/",
			getFeedbackType: "/api/itrack/iquality/feedbacktype",
			getQtrMIS: "/api/itrack/iquality/qtrmis"
		},
		masterscreen: {
			getMasterdropdown: "/api/itrack/masterScreenmap/masters/",
			getUserList: "/api/itrack/masterScreenmap/userlist",
			searchDuAndRole: "/api/itrack/masterScreenmap/userlistSearch",
			getMenuList: "/api/itrack/masterScreenmap/menulist",
			getMenuData: "/api/itrack/masterScreenmap/getMenuData",
			UpdateMenuData: "/api/itrack/masterScreenmap/insdelmenuaccess"
		},
		iaspire: {
			createEmployee: "/api/iaspire/userUpdation",
			getUserDetails: "/api/iaspire/getUserDetails",
			//Performance Type Mapping
			PerformanceType: {
				getPerformanceType: "/api/iaspire/getPerformanceTypeNotMapped",
				getHistoryPerformanceMap: "/api/iaspire/getHistoryPerformanceMap/",
				updatePerformanceType: "/api/iaspire/updatePerformanceTypeNotMap",
				getAppraisalType: "/api/iaspire/getapprtypeperfmap/"
			},
			scoresAndRating: {
				getData: "/api/iaspire/scoredata",
				filterData: "/api/iaspire/groupOption",
				createGroup: "/api/iaspire/createGroup",
				assignGroup: "/api/iaspire/assigngroup",
				getHistory: "/api/iaspire/getScoreRatingHistory/"
			},
			//Reporting Hierarchy
			ReportingHierarchy: {
				getReportingHierarchy: "/api/iaspire/getreportinghead",
				getDuFuHeadDetails: "/api/iaspire/getDuFuHeadDetails",
				getDUHFUHDropdownOptions: "/api/iaspire/getduhfuhoptions",
				updateDUHFUH: "/api/iaspire/updduhfuh"
			},
			//ML Management
			MLManagement: {
				getMLMappingDetails: "/api/iaspire/getMLMappingDetails",
				getMLViewMLDetails: "/api/iaspire/getViewMLDetails/"
			},
			//Email Links
			EmailTemplate: {
				getEmailTemplate: "/api/iaspire/getEmailTemplate/"
			},
			//Appraisal Setup
			AppraisalSetup: {
				getEmployeeAppraisalList: "/api/iaspire/getEmpAppraisalList",
				getAppraisalType: "/api/iaspire/getAppraisalTypeforApprSetup",
				updateEmpAppType: "/api/iaspire/updateEmpAppraisalDet",
				getHistoryAppraisalMap: "/api/iaspire/getEmpAppraisalHistory/",
				getDesigBandLevelList: "/api/iaspire/getdesigbandlevellist"
			},
			//QPR Template
			QPRTemplate: {
				getCombinationDetails: "/api/iaspire/getCombinationDetails",
				getBandLvlTemplateDetails: "/api/iaspire/getBandLvlTemplateDetails",
				getQprDDData: "/api/iaspire/getqprmst",
				createTemplate: "/api/iaspire/createtemplate",
				getQprTemplateData: "/api/iaspire/getqprtemplatedata",
				assignQPRTemplate: "/api/iaspire/assignqprtemplate"
			},
			//My Goals
			MyGoals: {
				getOrInsCurrentQuaterDetails:
					"/api/iaspire/getOrInsCurrentQuaterDetails",
				getQuaterList: "/api/iaspire/getQuaterList/",
				insOrUpdTransEntry: "/api/iaspire/insOrUpdTransEntry",
				getKraGoals: "/api/iaspire/getkragoals",
				getKraGoalsWithVersion: "/api/iaspire/getkragoalswithversion",
				getKraVersionList: "/api/iaspire/getkraversionlist/",
				getUserDetails: "/api/iaspire/getuserdetailsforkra/",
				copyPrevQuarterGoals: "/api/iaspire/copyprevquartergoals",
				getOrInsTransEntry: "/api/iaspire/getorinstransentry",
				getQPRStatus: "/api/iaspire/getqprstatusforquarter/",
				getLineItemforReport: "/api/iaspire/getlineitemforreport",
				getStatusList: "/api/iaspire/getstatuslist/",
				getStatusTrackerCurrent: "/api/iaspire/getstatustrackercurrent",
				getLineItemRating: "/api/iaspire/getlineitemrating/",
				insOrUpdateKraItems: "/api/iaspire/insorupdatekraitems",
				deleteKraItems: "/api/iaspire/delkralineitem/",
				submitGoals: "/api/iaspire/updatekrasubmit",
				getRating: "/api/iaspire/getrating/",
				statusTracker: {
					getRejectedStatus: "/api/iaspire/getstatusrejected"
				},
				selfScoreCard: {
					updatekraselfscore: "/api/iaspire/updatekraitemselfscore"
				},
				insAttachmentInfo: "/api/iaspire/insattachmentinfo",
				getAttachmentInfo: "/api/iaspire/getattachmentinfo/",
				getiAspireAzureFolderPath: "/api/iaspire/folderpath",
				reqForReopen: "/api/iaspire/reqforreopen",
				deleteAttachment: "/api/iaspire/deleteattachment",
				getAllComments: "/api/iaspire/getcomments/",
				getUserDOJ: "/api/iaspire/getdoj/"
			},
			//My Squad Goals
			MySquadGoals: {
				getSquadList: "/api/iaspire/mysquadlist",
				insertGetQuarterUserList: "/api/iaspire/quarteruserlist",
				getReopenReqList: "/api/iaspire/getreopenreqlist",
				getReopenReqType: "/api/iaspire/getreopenreqtype",
				aprRejeopenreq: "/api/iaspire/aprrejreopenreq",
				getQuaterDetails: "/api/iaspire/getQuarterList",
				scoreCardReview: {
					getTableData: "/api/iaspire/scorecardreview",
					getUserScoreRate: "/api/iaspire/userscorerate",
					insertQPRQuarterUserList: "/api/iaspire/insertqprquarterlist",
					kraApproveReject: "/api/iaspire/kraqprapprovereject",
					getRatingList: "/api/iaspire/getratinglist"
				},
				GoalApproval: {
					goalApproval: "/api/iaspire/updateapproveorreject",
					updateApproveorReject: "api/iaspire/updateapproveorreject"
				},
				Report: {
					subordinateList: "/api/iaspire/getsubordinate/"
				}
			},
			iAspireReports: {
				getFilter: "/api/iaspire/getFilterforPBReport",
				getPBRport: "/api/iaspire/getpbempReport",
				getRole: "/api/iaspire/getrole",
				getDateRange: "/api/iaspire/getclosingrange",
				setDateRange: "/api/iaspire/updateclosingrange",
				updateNotes: "/api/iaspire/updatepbnote",
				updateMovetoFin: "/api/iaspire/movetofinance",
				getFinReport: "/api/iaspire/getpbfinReport",
				getFinFilter: "/api/iaspire/getmasterdata",
				updateMovetopaid: "/api/iaspire/updatepbpaid",
				getaddscore: "/api/iaspire/getaddscore",
				updateHold: "/api/iaspire/updatehold",
				updateUnHold: "/api/iaspire/updateUnhold",
				getgift: "/api/iaspire/getgift",
				setgift: "/api/iaspire/setgift",
				getusergift: "/api/iaspire/getusergift",
				getexceldata: "/api/iaspire/getexcel"
			},
			AppraisalForm: {
				isEligible: "/api/iaspire/iseligible/",
				getAppEmpData: "/api/iaspire/getappempdetails/",
				getFinYearDropdown: "/api/iaspire/getfinyeardropdown/",
				getQuarterList: "/api/iaspire/getqualist/",
				getQuestionsList: "/api/iaspire/getquestionslist/",
				InsorUpdEmpDetails: "/api/iaspire/instorupdempdata",
				getFinYearKRADetails: "/api/iaspire/getfinyearkradetails",
				getAppStatusList: "/api/iaspire/getappstatuslist",
				getManagerEvaluationData: "/api/iaspire/getmanagerevaluationdata",
				getB3Designations: "/api/iaspire/getb3designations",
				getEmpYearlyAppDet: "/api/iaspire/getempyearlyappdet",
				updAppReviewData: "/api/iaspire/updappreviewdata",
				getB3BandLvl: "/api/iaspire/getb3bandlvl/",
				checkAppManEligible: "/api/iaspire/checkappmaneligible/"
			},
			FormAssessment: {
				getFilter: "/api/iaspire/getfilterformassessment",
				getQuestionforColumn: "/api/iaspire/getquestionformassessment",
				getData: "/api/iaspire/getformassessmentdata"
			},
			AppraisalReport: {
				getFilter: "/api/iaspire/getfilterappformreport",
				getReportData: "/api/iaspire/getappraisalformreport"
			}
		},
		salesPMO: {
			uploadtest: "/api/salespmo/uploads",
			newWIPReport: "/api/report/getWipReportNonWms",
			masters: {
				masterDD: "/api/salespmo/masters/"
			},
			planupload: "/api/salespmo/plandownload",
			customerGroup: {
				kamMapping: "/api/salespmo/createkamcustrel",
				getTableData: "/api/salespmo/kammaping",
				getHistory: "/api/salespmo/history"
			},
			journalRateEnrty: {
				getRateEntryTableData: "/api/salespmo/getrateentrystage",
				serviceDD: "/api/salespmo/service/",
				stageDD: "/api/salespmo/stage/",
				journalRate: "/api/salespmo/journalrate/insert",
				getRateEntry: "/api/salespmo/getrateentry/"
			},
			customerMapping: {
				reassignKamOrCm: "/api/salespmo/reassignkam"
			},
			changeRequest: {
				changeReqData: "/api/salespmo/changereq",
				updateKamReq: "/api/salespmo/kamupdatereq",
				getKamDetails: "/api/salespmo/kamdetails",
				apprRejectKAMChange: "/api/salespmo/apprchange"
			},
			segment: {
				getsegmentData: "/api/salespmo/getsegment",
				setsegment: "/api/salespmo/setsegment",
				deletesegment: "/api/salespmo/deletesegment",
				checksegmentData: "/api/salespmo/checksegment"
			},
			vertical: {
				getverticalData: "/api/salespmo/getvertical",
				setvertical: "/api/salespmo/setvertical",
				deletevertical: "/api/salespmo/deletevertical",
				checkvertical: "/api/salespmo/checkvertical"
			},
			service: {
				getserviceData: "/api/salespmo/getservice",
				setservice: "/api/salespmo/setservice",
				deleteservice: "/api/salespmo/deleteservice",
				checkservice: "/api/salespmo/checkservice"
			},
			report: {
				getUserMappedAndBaseDu: "/api/salespmo/reports",
				getProjectWiseReportData: "/api/salespmo/reports/project",
				getPlanVsActualReportData: "/api/salespmo/reports/project",
				getOrderInflowReportData: "/api/salespmo/reports/orderinflow",
				getOrderInflowFailureReportData:
					"/api/salespmo/reports/ordreinflowFailure",
				getAuditModulDD: "/api/salespmo/reports/auditmodule",
				getAuditSearchDD: "/api/salespmo/reports/jobdd",
				getAuditData: "/api/salespmo/reports/auditdata"
			},
			PlanUpload: {
				planupload: "/api/salespmo/planupload",
				exceptionExcel: "/api/salespmo/exceptiondata",
				currencyExchangeRate: "/api/salespmo/currencyexchangerate/",
				insorupdExchangeRate: "/api/salespmo/insorupdexchangerate",
				getYearDropdown: "/api/salespmo/getyeardropdown/",
				getPlanDetails: "/api/salespmo/plandetails",
				getUploadedPlan: "/api/salespmo/getuploadedplan",
				insAndGetFYear: "/api/salespmo/insorgetfyear"
			},
			rateEntry: {
				getDuByUserid: "/api/salespmo/getuserdu/",
				getDuFromKAMCust: "/api/salespmo/du",
				getCustomerByDuid: "/api/salespmo/customer/",
				getVerticalByCustomerid: "/api/salespmo/vertical/",
				getRateEntryData: "/api/salespmo/getrateentrystage",
				getRateEntryDD: "/api/salespmo/rateentrydd",
				createRateEntry: "/api/salespmo/insertrateentry",
				getRateEntryRecords: "/api/salespmo/getrateentry/",
				getJobRateEntryActuals: "/api/salespmo/actuals/",
				getMonthYear: "/api/salespmo/monthyr",
				getAdjRate: "/api/salespmo/adjdata/",
				insertAdjRate: "/api/salespmo/rateadj",
				deleteAdjCost: "/api/salespmo/deleteadj/"
			},
			Masters: {
				getMasterData: "/api/salespmo/getmasterdata/",
				editMasterData: "/api/salespmo/updatemasterdata",
				inserttMasterData: "/api/salespmo/addmasterdata",
				deleteMasterData: "/api/salespmo/deletemasterdata"
			},
			LockUnlock: {
				getWorkOrderList: "/api/salespmo/getworkorderlist/",
				uploadList: "/api/salespmo/updateworkorderlist",
				exceptiondata: "/api/salespmo/getexceptiondata",
				updateLockUnlock: "/api/salespmo/updateworkoderlockunlock",
				getWorkorderHistory: "/api/salespmo/getworkorderhistory/"
			},
			rateConfig: {
				getServiceDD: "/api/salespmo/rateconfig/service/",
				getCategoryDD: "/api/salespmo/rateconfig/category",
				getStageDD: "/api/salespmo/rateconfig/stage/",
				insertRate: "/api/salespmo/rateconfig",
				checkComb: "/api/salespmo/rateconfig/comb/",
				insertInvoice: "/api/salespmo/invoicedesc",
				getInvoice: "/api/salespmo/rateconfig/invoice",
				getRateConfigTable: "/api/salespmo/rateconfig/table",
				getRateConfigRateData: "/api/salespmo/rateconfig/rate",
				getRateConfigInvoiceData: "/api/salespmo/rateconfig/invoicedesc",
				getInvoiceFiledData: "/api/salespmo/rateconfig/invoicefield",
				getMasterTemplate: "/api/salespmo/rateconfig/template",
				insertTemplate: "/api/salespmo/rateconfig/template/insert",
				getIOUBRTableData: "/api/salespmo/rateconfig/ioubr"
			},
			rfi: {
				raiseRfiTable: "/api/salespmo/rfi/raiserfi",
				getWoDetails: "/api/salespmo/rfi/jobdetails/",
				getRateEntryForRFI: "/api/salespmo/rfi/rateentry",
				createRFI: "/api/salespmo/rfi/create",
				insertRFIFile: "/api/salespmo/rfi/rfifile",
				getRFIDetails: "/api/salespmo/rfi/view/",
				getRFIArticleDetails: "/api/salespmo/rfi/article/",
				approveRejectRFI: "/api/salespmo/rfi/apprej",
				delrfiattachment: "/api/salespmo/rfi/delrfiattachment"
			},
			ACSAuto: {
				vendorBillingReportUpload: "/api/salespmo/rfi/ACS"
			},
			Pearson: {
				PriceGrid: {
					excelUpload: "/api/salespmo/pearson/pricegridupload",
					getFileDetails: "/api/salespmo/pearson/getfiledetails",
					getFileLineItemDetails: "/api/salespmo/pearson/getfileitems"
				},
				RateEntry: {
					checkIsIncomingAndStageComplete: "/api/salespmo/pearson/checkincomingstageisexist/",
					getExcelMasters: "/api/salespmo/pearson/getmasterfromexcel/",
					getUBRStage: "/api/salespmo/pearson/getubrstagewithwoid/",
					InsorUpdPearsonRateEntry: "/api/salespmo/pearson/insorupdrateentry"
				}
			}
		},
		odoo: {
			report: {
				getUbrFailureReport: "/api/odoo/ubrfailurereport",
				getRaiseRFIReport: "/api/odoo/invoicefailurereport"
			},
			invoice: {
				sendInvoiceOdoo: "/api/odoo/sendinvoice"
			}
		},
		cupAuthorUpload: {
			getCustomerMaster: "/api/cupauthor/customer",
			getJournalByCustomer: "/api/cupauthor/journal/",
			checkArticleByJournal: "/api/cupauthor/article/",
			logUploadfile: "/api/cupauthor/logupload",
			uploadFileToBlob: "/api/cupauthor/uploadfile",
			downloadFileFromBlob: "/api/cupauthor/downloadblobfile"
		}
	},
	cupelement_rest: {
		cupElement: {
			getMaster: "/api/cupelement/getMaster/",
			createJob: "/api/cupelement/createnewjob",
			getunclaimedjob: "/api/cupelement/getunclaimedjob/",
			getclaimedjob: "/api/cupelement/getclaimedjob/",
			getstatusdropdown: "/api/cupelement/getstatus",
			fileUploadPath: "/api/cupelement/getfileuploadpath",
			addFilePath: "/api/cupelement/addjobfilepath",
			getcheckseries: "/api/cupelement/getcheckseries",
			getJobDetails: "/api/cupelement/getJobDetails/",
			getNotes: "/api/cupelement/getNotes",
			insNotes: "/api/cupelement/insNotes",
			getRoleAcronym: "/api/cupelement/getroleacronym/",
			getexportlist: "/api/cupelement/getexportlist",
			getRoleJobStatus: "/api/cupelement/getrolejobstatus/",
			updateJobStatus: "/api/cupelement/updatejobstatus",
			saveMSedit: "/api/cupelement/updatemsedit",
			getMSEdit: "/api/cupelement/getmsedit/",
			savePTedit: "/api/cupelement/updateptedit",
			getPTEdit: "/api/cupelement/getptedit/",
			saveCTedit: "/api/cupelement/updatectedit",
			getCTEdit: "/api/cupelement/getctedit/",
			getFolderName: "/api/cupelement/getfoldername",
			checkSeriesExist: "/api/cupelement/checkseriesexist/",
			checkSeriesCodeExist: "/api/cupelement/checkseriescodeexist/",
			savePMedit: "/api/cupelement/updatepmedit",
			createSeries: "/api/cupelement/createSeriesMaster",
			updateSeries: "/api/cupelement/updateSeriesMaster",
			getSeriesDetails: "/api/cupelement/getseriesmasterdetails",
			getSeriesDataDetails: "/api/cupelement/getseriesdatadetails/",
			getPMopenJobs: "/api/cupelement/getPMOpenJobs/",
			reassignPMSeries: "/api/cupelement/reassignPMSeries",
			removeSeries: "/api/cupelement/removeSeries/",
			getJobHistory: "/api/cupelement/getJobHistory/",
			getFilePath: "/api/cupelement/getFilePath",
			updateFileInDB: "/api/cupelement/updateFileInDB",
			unclaimjob: "/api/cupelement/unclaimjob",
			raiseQuery: "/api/cupelement/raiseQuery",
			queryfiledetails: "/api/cupelement/queryfileuploaddetails",
			getQueryJobBased: "/api/cupelement/getquerybasedjob/",
			updatePMstatus: "/api/cupelement/updatepmstatus",
			updatemscleanup: "/api/cupelement/updatemscleanup",
			updateHistoryforUnclaim: "/api/cupelement/updatehistoryforunclaim",
			getteamjobdetails: "/api/cupelement/getteamjobdetails/",
			getEmailIntroPreview: "/api/cupelement/getEmailIntroPreview/",
			sendEmailIntro: "/api/cupelement/sendEmailIntro",
			getOpenedQueries: "/api/cupelement/getopenedqueries",
			getRaisedQueries: "/api/cupelement/getraisedquery",
			getRejectJob: "/api/cupelement/getrejectedjob/",
			getjobcompletestatus: "/api/cupelement/getjobcompletestatus/",
			handlePdfDownload: "/api/cupelement/handlePdfDownload",
			getPMDetails: "/api/cupelement/getPMDetails/",
			getPMEdit: "/api/cupelement/getpmedit/",
			getQueryDetails: "/api/cupelement/getQueryDetails/",
			responseQuery: "/api/cupelement/responseQuery",
			createReject: "/api/cupelement/createReject",
			getRejectJobDetails: "/api/cupelement/getrejectjobdetails/",
			reSubmitJob: "/api/cupelement/reSubmitJob",
			getopenquery: "/api/cupelement/getopenquery/"
		}
	},
	// iAlt
	iAlt_rest: {
		getiAltTaskList: "/api/ialt/getiAltTaskList",
		getiAltChapterList: "/api/ialt/getiAltChapterList",
		triggerIaltWorkflow: "/api/ialt/triggerIaltWorkflow",
		generalActionProcess: "/api/ialt/generalActionProcess",
		workflowActionProcess: "/api/ialt/workflowActionProcess",
		getImageClassification: "/api/ialt/getImageClassification",
		getAltTextGeneration: "/api/ialt/getAltTextGeneration",
		updateAltTextGeneration: "/api/ialt/updateAltTextGeneration",
		reAltTextGeneration: "/api/ialt/reAltTextGeneration",
		getBookMasterFields: "/api/ialt/getBookMasterFields",
		getAllClassification: "/api/ialt/getAllClassification",
		getAllPrompt: "/api/ialt/getAllPrompt",
		checkAssignedTask: "/api/ialt/checkAssignedTask",
		taskAssign: "/api/ialt/taskAssign",
		getOptionList: "/api/ialt/getOptionList",
		createiAltBookCode: "/api/ialt/createiAltBookCode",
		getBookMasterDatas: "/api/ialt/getBookMasterDatas",
		deleteBookMasterDatas: "/api/ialt/deleteBookMasterDatas",
		getClientOptions: "/api/ialt/getClientOptions",
		workorderCreation: "/api/ialt/workorderCreation",
		getChapterMasterDatas: "/api/ialt/getChapterMasterDatas",
		deleteChapter: "/api/ialt/deleteChapter",
		getBookListByIdForPm: "/api/ialt/getBookListByIdForPm",
		getiAltReportData: "/api/ialt/getiAltReportData",
		getiAltJobsData: "/api/ialt/getiAltJobsData",
		getiAltDispatchData: "/api/ialt/getiAltDispatchData",
		getiAltWIPData: "/api/ialt/getiAltWIPData",
		getiAltYTSData: "/api/ialt/getiAltYTSData",
		getiAltBookwise: "/api/ialt/getiAltBookwise",
		getiAltXlReport: "/api/ialt/getiAltXlReport",
		getReportOptionList: "/api/ialt/getReportOptionList",
		getiAltWIPReportTwo: "/api/ialt/getiAltWIPReportTwo",
		getiAltWIPChapterReport: "/api/ialt/getiAltWIPChapterReport",
		iAltChapterCreation: "/api/ialt/iAltChapterCreation",
		updateChapterCreation: "/api/ialt/updateChapterCreation",
		getiAltIncomingChapters: "/api/ialt/getiAltIncomingChapters",
		iAltIncomingFilesOperations: "/api/ialt/iAltIncomingFilesOperations",
		iAltTriggerChapter: "/api/ialt/iAltTriggerChapter",
		getiAltAssetReportData: "/api/ialt/getiAltAssetReportData",
		getiAltBookWiseReport: "/api/ialt/getiAltBookWiseReport",
		getiAltChapterWiseReport: "/api/ialt/getiAltChapterWiseReport",
		getiAltImageWiseReport: "/api/ialt/getiAltImageWiseReport",
		getDashboardReportOptionList: "/api/ialt/getDashboardReportOptionList",
		getDashboardData: "/api/ialt/getDashboardData",
		getImageCountInfo: "/api/ialt/getImageCountInfo",
		checkiAltAvailability: "/api/ialt/checkiAltAvailability",
		taskAssignForTL: "/api/ialt/taskAssignForTL",
		getiAltSignalAudit: "/api/ialt/getiAltSignalAudit",
		iAltJobSummaryRetrigger: "/api/ialt/iAltJobSummaryRetrigger",
		getiAltSignaleAuditHistory: "/api/ialt/getiAltSignaleAuditHistory",
		getFolderStructureForIalt: "/api/ialt/getFolderStructureForIalt",
		iAltDirectDespatch: "/api/ialt/iAltDirectDespatch",
		iAltDirectDespatchWithExcel: "/api/ialt/iAltDirectDespatchWithExcel",
		getMetadata: "/api/ialt/iAltJobCreationClientPII",
		iAltManulWoFilesDownload: "/api/ialt/iAltManulWoFilesDownload",
		iAltBookWiseReportGenerate: "/api/ialt/iAltBookWiseReportGenerate",
		altextGenerationJobProcess: "/api/signal/altextGenerationJobProcess",
		deleteJobAuditHistory: "/api/ialt/iAltDeleteJobAuditHistory",
		ialtGetComplexity: "/api/ialt/getComplexity",
		ialtUpdateComplexity: "/api/ialt/updateComplexity",
		ialtCreateComplexity: "/api/ialt/createComplexity",
		ialtGetPlaceholder: "/api/ialt/getPlaceholder",
		ialtUpdatePlaceholder: "/api/ialt/updatePlaceholder",
		ialtCreatePlaceholder: "/api/ialt/createPlaceholder",
		iAltZIPDownloadBlobFolder: "/api/ialt/iAltZIPDownloadBlobFolder",
		iAltFileUploadBlobFolder: "/api/ialt/document/checkin",
		iAltFileDownloadBlobFolder: "/api/ialt/document/ZIPDownloadBlobFolder",
		iAltTandeIntegration: "/api/ialt/tandeIntegration",
		getiAltJobsOverallData: "/api/ialt/getiAltJobsOverallData",
		createiAltQuery: "/api/ialt/createiAltQuery",
		queueTriggerLog: "/api/ialt/queueTriggerLog",
		autoJobFailedRetrigger: "/api/ialt/autoJobFailedRetrigger",
		acknowledgmentLog: "/api/ialt/acknowledgmentLog",
		ackFailedRetrigger: "/api/ialt/ackFailedRetrigger",
		getiAltBookDetails: "/api/ialt/getiAltBookDetails",
		getiAltComplexityXlReport: "/api/ialt/getiAltComplexityXlReport",
		checkPIIExists:"/api/ialt/checkPIIExists",
        getiAltQueryData: "/api/ialt/getiAltQueryData",
	},
	workOrder_dynamic: {
		getuserDu: "/api/woi/getuserdu",
		gettabinfofieldDetails: "/api/woi/gettabifofielddetails",
		checkIsDUWMS: "/api/woi/checkisduwms/",
		getStageDropdown: "/api/woi/getStageDropdown",
		getServiceDropdown: "/api/woi/getServiceDropdown/",
		createStage: "/api/woi/insertdynamicstage",
		createDynamicWO: "/api/woi/createdynamicwo",
		getStageDetails: "/api/woi/getstagedetails/",
		updateStage: "/api/woi/updatestage",
		checkStageStatus: "/api/woi/getstagestatus/",
		removeStage: "/api/woi/removestage",
		getdetails: "/api/woi/getswnorms",
		updatetaskstatus: "/api/woi/updatestatus",
		getandUpdateWOPMContact: "/api/woi/getupdatewopmcontact/",
		getDynamicWODetails: "/api/woi/getdynwodetails",
		getiTrackCustMAPId: "/api/woi/getitrackcustmapid",
		getIncomingDropdown: "/api/woi/getdropdown/",
		insertSubJob: "/api/woi/insertsubjobdetail",
		getSubJobDetails: "/api/woi/getsubjobdetail",
		checkStageExist: "/api/woi/checkstageexist",
		updateSubJob: "/api/woi/updatesubjobdetail",
		assignstage: "/api/woi/insertsubincoming",
		getAssignStageDet: "/api/woi/getassignstage",
		iTrackClaim: "/api/woi/claimsubjobeventlog",
		updateLogisticEntry: "/api/woi/updatesubjobeventlog",
		getNonWmsTaskDetails: "/api/woi/getchapterdetail",
		getsubJobDropdown: "/api/woi/getsubjobdropdown",
		getUnallocatedArticleandIssue: "/api/woi/getunallocatedarticleandissue",
		createDynamicWOBulk: "/api/woi/createdynamicbulkwo",
		getPMandCMOptions: "/api/woi/getpmandcmoptions",
		checkProductionDispatch: "/api/woi/checkproductiondispatch",
		updatechecklist: "/api/woi/updatechecklist",
		getKAMOptions: "/api/woi/getkamoptions",
		rejectManualEntry: "/api/woi/rejectcustomerdispatch",
		checkflowtype: "/api/woi/checkflowtype/",
		getRoleDetails: "/api/woi/getroleacronym/",
		updateStageDuedate: "/api/woi/updateduedate"
	},
	customerSetup: {
		getActiveSections: "/api/customersetup/getactivesections",
		CheckIsExist: "/api/customersetup/checkisexist",
		InsertCustomerMapping: "/api/customersetup/insertcustmapping",
		getActiveInfos: "/api/customersetup/getactiveinfos/",
		UpdateWOConfig: "/api/customersetup/updatewoconfig",
		getActiveInfoFields: "/api/customersetup/getactivefields",
		insertInfoFields: "/api/customersetup/insertfields",
		getActiveCustomerSetup: "/api/customersetup/getactivecustomersetup",
		deleteCustomerSetup: "/api/customersetup/deletecustomersetup",
		getCustomerType: "/api/customersetup/getduflowtype/",
		createWorkflow: "/api/customersetup/createworkflow",
		getWorkflow: "/api/customersetup/getworkflow/",
		getScreenid: "/api/customersetup/getscreenid/",
		getAllWorkFlow: "/api/customersetup/getallworkflow/",
		getWOUserList: "/api/customersetup/getwouserlist/",
		insertWOUser: "/api/customersetup/inswouser",
		updateWOUser: "/api/customersetup/updwouser",
		// Production Despatch Mail Setup
		getMailList: "/api/customersetup/getmaillist",
		getCCMailDD: "/api/customersetup/getccmail/",
		updCCMail: "/api/customersetup/insccmail"
	}
};
